import type { Metadata } from 'next';
import { Geist_Mono, Inter, Instrument_Serif } from 'next/font/google';
import { SmoothScroll }   from '../components/gsap/SmoothScroll';
import { CustomCursor }   from '../components/gsap/CustomCursor';
import { PageTransition } from '../components/gsap/PageTransition';
import Navbar from '../components/global/Navbar';
import Footer from '../components/global/Footer';
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-display",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={`${inter.variable} ${instrumentSerif.variable} ${geistMono.variable} font-sans antialiased`}>
        <CustomCursor />
        <Navbar />
        <PageTransition />
        <SmoothScroll>
          <main className="min-h-screen">
            {children}
          </main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
